name: Trigger auto deployment for portfolionextjs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/portfolionextjs-AutoDeployTrigger-f34ac056-3b70-4904-9df1-323aa1ccc88d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PORTFOLIONEXTJS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrytestcontainerapp.azurecr.io
          registryUsername: ${{ secrets.PORTFOLIONEXTJS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PORTFOLIONEXTJS_REGISTRY_PASSWORD }}
          containerAppName: portfolionextjs
          resourceGroup: testcontainerapp_rg
          imageToBuild: containerregistrytestcontainerapp.azurecr.io/portfolionextjs:${{ github.sha }}
          
            

     

